### ISSUE TITLE
local model not running - Ollama "HUGGINGFACE_API_KEY not found in .env file"

### ISSUE THREAD

**Issue by returnvenky** [haseeb-heaven/code-interpreter#20]
**Describe the bug**

Unable to use OLLAMA local model

**To Reproduce**
1. Install using pip
2. interpreter -m local-model -md code -dc
 3. Error 
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\x\.conda\envs\xy\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Users\x\.conda\envs\xy\Lib\site-packages\open_code_interpreter\interpreter.py", line 56, in main
    interpreter = Interpreter(args)
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\x\.conda\envs\xy\Lib\site-packages\open_code_interpreter\libs\interpreter_lib.py", line 49, in __init__
    self.initialize()
  File "C:\Users\x\.conda\envs\xy\Lib\site-packages\open_code_interpreter\libs\interpreter_lib.py", line 85, in initialize
    self.initialize_client()
  File "C:\Users\x\.conda\envs\xy\Lib\site-packages\open_code_interpreter\libs\interpreter_lib.py", line 127, in initialize_client
    raise Exception(f"{api_key_name} not found in .env file.")
Exception: HUGGINGFACE_API_KEY not found in .env file.

**Expected behavior**
App to start 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser edge 

Local-model.config

# The temperature parameter controls the randomness of the model's output. Lower values make the output more deterministic.
temperature = 0.1

# The maximum number of new tokens that the model can generate.
max_tokens = 2048

# The start separator for the generated code.
start_sep = ```

# The end separator for the generated code.
end_sep = ```

# If True, the first line of the generated text will be skipped.
skip_first_line = True

# The model used for generating the code.
#HF_MODEL = ollama/qwen2.5-coder

api_base = https://localhost:11434/api/generate

**Comment by haseeb-heaven** [comment]
Hi,
I will look at this issue.

Please provide full command you used to run code interpreter.

If you have any logs then you can attach them

**Comment by returnvenky** [comment]
(xy) C:\Users\X>interpreter -m local-model -md code -dc
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\X\.conda\envs\xy\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Users\X\.conda\envs\xy\Lib\site-packages\open_code_interpreter\interpreter.py", line 56, in main
    interpreter = Interpreter(args)
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\x\.conda\envs\xy\Lib\site-packages\open_code_interpreter\libs\interpreter_lib.py", line 49, in __init__
    self.initialize()
  File "C:\Users\x\.conda\envs\xy\Lib\site-packages\open_code_interpreter\libs\interpreter_lib.py", line 85, in initialize
    self.initialize_client()
  File "C:\Users\x\.conda\envs\xy\Lib\site-packages\open_code_interpreter\libs\interpreter_lib.py", line 127, in initialize_client
    raise Exception(f"{api_key_name} not found in .env file.")
Exception: HUGGINGFACE_API_KEY not found in .env file.

(xy) C:\Users\x>

this the code form the terminal, im using conda env. 
i installed using pip

**Comment by haseeb-heaven** [comment]
This issue is fixed in this [commit](https://github.com/haseeb-heaven/code-interpreter/commit/79e4f60c243eefcfab6d0041b0e582a02c96b695)

**Comment by haseeb-heaven** [comment]
> (xy) C:\Users\X>interpreter -m local-model -md code -dc Traceback (most recent call last): File "", line 198, in _run_module_as_main File "", line 88, in _run_code File "C:\Users\X.conda\envs\xy\Scripts\interpreter.exe__main__.py", line 7, in File "C:\Users\X.conda\envs\xy\Lib\site-packages\open_code_interpreter\interpreter.py", line 56, in main interpreter = Interpreter(args) ^^^^^^^^^^^^^^^^^ File "C:\Users\x.conda\envs\xy\Lib\site-packages\open_code_interpreter\libs\interpreter_lib.py", line 49, in **init** self.initialize() File "C:\Users\x.conda\envs\xy\Lib\site-packages\open_code_interpreter\libs\interpreter_lib.py", line 85, in initialize self.initialize_client() File "C:\Users\x.conda\envs\xy\Lib\site-packages\open_code_interpreter\libs\interpreter_lib.py", line 127, in initialize_client raise Exception(f"{api_key_name} not found in .env file.") Exception: HUGGINGFACE_API_KEY not found in .env file.
> 
> (xy) C:\Users\x>
> 
> this the code form the terminal, im using conda env. i installed using pip

PIP has not the latest version, just use this build from repo.

**Comment by haseeb-heaven** [comment]
Fixed API Key requirements for Ollama models. The interpreter no longer requires HUGGINGFACE_API_KEY when running local or ollama models.
